### PR TITLE
Add material shadows

### PR DESCRIPTION
**Pull request by GriNAME**

### CODE REVIEW

**Comment by BrunnerLivio** [comment]
Thank you very much!

One last thing; don't forget to update README.md 
```
md-brown-*
md-grey-*
md-blue-grey-*
md-black
md-white
.....
md-shadow-1dp
...
```

**Comment by GriNAME** [comment]
Look, what if make the snippets with "box-shadow:" Because if someone is using Emmet he will get "box-shadow: some properties". Try it

**Comment by BrunnerLivio** [comment]
@GriNAME  I'm sorry, but I don't exactly understand what you mean?

**Comment by GriNAME** [comment]
@BrunnerLivio sorry I was at work and wrote not all. I mean if you use Emmet you will get this code
input:
**bxsh**
output:
**box-shadow: inset hoff voff blur color**

So you will need to delete all values in box-shadow properties

**Comment by BrunnerLivio** [comment]
@GriNAME I see. 
So you suggest you want to get, for example `box-shadow: 0 2px 2px 0 rgba(0,0,0,.14),0 3px 1px -2px rgba(0,0,0,.2),0 1px 5px 0 rgba(0,0,0,.12)` when you type `md-shadow-2dp`, instead of just the properties, am I right?

**Comment by GriNAME** [comment]
Yep) But I'm not quite sure about that decision, so decide to consult with you.

**Comment by BrunnerLivio** [comment]
Pros:
- Less typing for a user
- No Emmet removing

Cons:
- Little bit inconsistent, because all the color-snippets are just properties (#fffff or whatever), but shadows would be attribute and property

I cant find more Pros/Cons, so I would go with `box-shadow: xxx`.

If someone does not like it, he should create a justified issue.

**Pull request merged**
