### PR TITLE
Add colors for text and icons

### PR DESCRIPTION
**Pull request by GriNAME**

### CODE REVIEW

**Comment by GriNAME** [comment]
@BrunnerLivio сan you add all the changes to the README.md file? I've added this [things ](https://material.io/guidelines/style/color.html#color-text-background-colors). (I don't have a good English to do it myself)

**Comment by BrunnerLivio** [comment]
Thanks for the PR!

I merge this, but are you okay when I change hex to numeric values? Like `rgba(#FFF, 1)` to `rgba(255, 255, 255, 1)`? Or is it a special reason you want to have hex there?

**Comment by GriNAME** [comment]
Oh it's okay) it doesn't matter)

**Comment by GriNAME** [comment]
Cool))) Now it seems like a great plugin for VS Code)))

**Pull request merged**
